### ISSUE TITLE
1.20 support-ipv6-dualstack test result

### ISSUE THREAD

**Issue by Stevent-fei** [AliyunContainerService/ackdistro#113]
Summarizing 6 Failures:

[Fail] [sig-apps] Daemon set [Serial] [It] should rollback without unnecessary restarts [Conformance]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:418

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [It] validates resource limits of pods that are allowed to run  [Conformance]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:325

[Fail] [sig-scheduling] SchedulerPreemption [Serial] [It] validates lower priority pod preemption by critical pod [Conformance]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [It] validates that there exists conflict between pods with same hostPort and protocol but one using 0.0.0.0 hostIP [Conformance]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:1123

[Fail] [sig-scheduling] SchedulerPreemption [Serial] [It] validates basic preemption works [Conformance]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113

[Fail] [sig-scheduling] SchedulerPredicates [Serial] [It] validates that NodeSelector is respected if not matching  [Conformance]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:438

Ran 309 of 5667 Specs in 6177.341 seconds
FAIL! -- 303 Passed | 6 Failed | 0 Pending | 5358 Skipped
--- FAIL: TestE2E (6177.45s)
FAIL

Ginkgo ran 1 suite in 1h42m59.12647752s
Test Suite Failed
2022/07/01 07:40:54 Saving results at /tmp/sonobuoy/results
2022/07/01 07:40:54 running command: exit status 1
+ ret=1
+ exit 1

**Comment by ankushgoel27** [comment]
i am doing a bug bounty test. please don't block me as this is not malicious
