### ISSUE TITLE
Pulling the image from sea.hub:5000 reports an error

### ISSUE THREAD

**Issue by qingfengfenga** [AliyunContainerService/ackdistro#13]
Pulling the image from `sea.hub:5000` reports an error

`http: server gave HTTP response to HTTPS client`

You need to modify the `/etc/docker/daemon.json` file, add `{ "insecure-registries":["sea.hub:5000"] }` configuration, then load the configuration and restart docker

```
systemctl daemon-reload
systemctl restart docker
```

Run the installation command again, the installation is complete

```
# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE   ERROR
etcd-2               Healthy   ok
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-0               Healthy   ok
etcd-1               Healthy   ok
```

**Comment by VinceCui** [comment]
Are you using your own docker?

**Comment by qingfengfenga** [comment]
yes i use root user and new machine

**Comment by VinceCui** [comment]
Can you create a new env, and install again. If this error occurs again, give us your context.

**Comment by qingfengfenga** [comment]
Sorry, it's my problem, the system image I use has Docker installed by default, and it's not cleaned up, thank you
