### ISSUE TITLE
Security Bug

### ISSUE THREAD

**Issue by ankushgoel27** [AliyunContainerService/ackdistro#135]
Hi,

I submitted a security bug on security.alibaba.com related to this GitHub repository but I haven't heard anything back from them. navigating the security.alibaba.com website is also very tough as it always error's out. 

I see that you have disabled the aliyun/Alibaba cloud credentials. Can you please help me in communicating with the security team?

**Comment by VinceCui** [comment]
Thanks. The security team has contacted me, we are still working on it, we will give you an answer later

**Comment by ankushgoel27** [comment]
I see that you have already fixed the issue by modifying both auto-build.yml and test.yml files by including an issue number and limiting that issue number to only collaborators. Let me know if you need any more help. My email id is - ankushgoel27@gmail.com

**Comment by ankushgoel27** [comment]
Hi,

I just want to mention that limiting the workflow to a particular issue id and only allowing collaborators to comment on that issue id is not a foolproof solution. Anyone who submits a pull request to this project and that pull request gets accepted becomes a collaborator on the ackdistro project and thus can comment and execute that vulnerable workflow.

I got a response from the security team. I will close this issue now.
