### ISSUE TITLE
What is the roadmap of ACK-distro?

### ISSUE THREAD

**Issue by allencloud** [AliyunContainerService/ackdistro#14]
Could ACK-distro provide the roadmap details?

Will we support kubernetes 1.21 soon?

**Comment by luckyfengyong** [comment]
@allencloud ackdistro follows the Kubernetes version strategy of ACK. ACK won't support 1.21 but 1.20 and 1.22. Please refer to https://help.aliyun.com/document_detail/115453.html for the details of the Kubernetes version strategy of ACK.

**Comment by allencloud** [comment]
> @allencloud ackdistro follows the Kubernetes version strategy of ACK. ACK won't support 1.21 but 1.20 and 1.22. Please refer to https://help.aliyun.com/document_detail/115453.html for the details of the Kubernetes version strategy of ACK.

Thanks a lot for the link sharing. That is great.
