### ISSUE TITLE
 https://sea.hub:5000/v2/ Timeout

### ISSUE THREAD

**Issue by incidunt** [AliyunContainerService/ackdistro#15]
level=warning msg="Error getting v2 registry: Get https://sea.hub:5000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"

**Comment by VinceCui** [comment]
Please use our recommended issue template, which will give us more information.

**Comment by VinceCui** [comment]
New version has fix this bug.
