### ISSUE TITLE
`kubectl top node` fails.

### ISSUE THREAD

**Issue by HaiyangDING** [AliyunContainerService/ackdistro#16]
Bug Report
---

Type: *bug report*

### What happened

kubectl top node

would fail with 

"error: metrics not available yet"

### What you expected to happen

kubectl top node 

returns the node resource usage normally

### How to reproduce it (as minimally and precisely as possible)

kubectl top node

### Environment
- ACK Distro version:
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

```
[root@iZm5ebh5r61znlcl60iqumZ ~]# kubectl get node
NAME                      STATUS   ROLES                  AGE   VERSION
izm5ebh5r61znlcl60iqumz   Ready    control-plane,master   32d   v1.20.4-aliyun.1
[root@iZm5ebh5r61znlcl60iqumZ ~]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
[root@iZm5ebh5r61znlcl60iqumZ ~]# sealer version
{"gitVersion":"v0.5.2","gitCommit":"858ece9","buildDate":"2021-12-13 03:22:26","goVersion":"go1.14.15","compiler":"gc","platform":"linux/amd64"}
[root@iZm5ebh5r61znlcl60iqumZ ~]# uname -a
Linux iZm5ebh5r61znlcl60iqumZ 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by HaiyangDING** [comment]
Temporary workround:

execute `echo "readOnlyPort: 10255" >> /var/lib/kubelet/config.yaml && systemctl restart kubelet` on every node. 

Wait for a while and it should work.

**Comment by VinceCui** [comment]
We have fix this bug.
