### ISSUE TITLE
no need to re-download build context  if it is already exist.

### ISSUE THREAD

**Issue by kakaZhou719** [AliyunContainerService/ackdistro#174]
Issue Description
---

Type: *feature request*

### Describe what feature you want

hi, @Stevent-fei @VinceCui ,

so fast when i use this repo to build ackd sealer image. 

while i run build cmd: `bash build.sh v1.22.15-aliyun.1  v1.1 true` ,  every time I re-run, this script will re-download the corresponding oss file.

Can we optimize this to make build more faster ？

**Comment by VinceCui** [comment]
you can use export SKIP_DOWNLOAD_BINS=true, to skip download binary file.
