### ISSUE TITLE
What is the version policy of ACK distro?

### ISSUE THREAD

**Issue by allencloud** [AliyunContainerService/ackdistro#28]
I found that currently ACK-distro has no version policy there, such as ack-distro 0.1.0 or 1.0.0, or conclude a detailed set of feature.

I think if ack-distro has a detailed plan fo version policy, it could provide more confidence when users are judging whether to adopt it.

**Comment by luckyfengyong** [comment]
@allencloud Please refer to https://github.com/AliyunContainerService/ackdistro/blob/main/docs/FAQ.md for the version policy. We will put it into a standalone user doc to make it more obvious. 

Please also let us know if you have any question during evaluating ACK Distro.
