### ISSUE TITLE
When do you have ARM arch support ready?

### ISSUE THREAD

**Issue by cuericlee** [AliyunContainerService/ackdistro#4]
Issue Description
When do you have ARM arch support ready?
---

Type: *feature request*
ARM arch support

**Comment by VinceCui** [comment]
We are doing this work, Maybe February.

**Comment by u2bo** [comment]
> 

arm64 is ready？

**Comment by luckyfengyong** [comment]
@u2bo Sorry for the delayed response. The arm64 platform will be supported in the next release together with Kubernetes 1.22 and other features, sometime in Apr.

**Comment by VinceCui** [comment]
Hi, we have release ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/ackdistro:v1-20-4-ack-4, which support Arm64 now.
